/*
The MIT License (MIT)

Copyright (c) 2007 Roger Hill

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files 
(the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, 
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE 
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Text;

using DAL.Framework.SqlMetadata;

namespace AutoCodeGenLibrary
{
    public abstract class CodeGeneratorBase
    {
        // figure out tab size
        protected int _VisualStudioTabSize = Convert.ToInt32(ConfigurationManager.AppSettings["VisualStudioTabSize"]);

        public CodeGeneratorBase() { }

        protected string GenerateAuthorNotice()
        {
            return $"Generated by Jolly Roger's Autocode Generator on {DateTime.Now}";
        }

        protected string AddTabs(int tabCount)
        {
            if (tabCount < 0)
                throw new ArgumentException($"Cannot generate a string of {tabCount} tabs");

            var output = string.Empty;

            while (tabCount > 0)
            {
                output += '\t';
                tabCount--;
            }

            return output;
        }

        protected int GetLongestColumnLength(SqlTable sqlTable)
        {
            if (sqlTable == null)
                throw new ArgumentException("Cannot compute longest column of a null table.");

            int longest_column_length = 0;

            foreach (var column in sqlTable.Columns.Values)
            {
                if (column.Name.Length > longest_column_length)
                    longest_column_length = column.Name.Length;
            }

            return longest_column_length;
        }

        protected string PadVariableName(string input, int longestStringLength, int additionalCharacters, int tabSize)
        {
            longestStringLength += tabSize + additionalCharacters;
            int pad_length = longestStringLength + (tabSize - (longestStringLength % tabSize));
            return input.PadRight(pad_length, ' ');
        }

        protected string FindIdField(SqlTable sqlTable)
        {
            // occasionally we might need to figure out a primary key for a table.
            // this method isn't perfect, but its a decent stab at the problem.
            // grab the first PK we have. If there is no PKs defined, grab the
            // first int we find.

            if (sqlTable.PkList.Count == 0)
            {
                foreach (var column in sqlTable.Columns)
                {
                    if (column.Value.BaseType == eSqlBaseType.Integer)
                        return column.Key;
                }

                // still here? no matches then...
                return string.Empty;
            }
            else
            {
                return sqlTable.PkList[0].Name;
            }
        }

        protected string FindNameField(SqlTable sqlTable)
        {
            // occasionally we might need to figure out a friendly name field for 
            // a table. this method isn't perfect, but its a decent stab at the problem.
            // grab the first text field we have, and hope for the best.

            foreach (var column in sqlTable.Columns)
            {
                if (column.Value.BaseType == eSqlBaseType.String)
                    return column.Key;
            }

            // still here? no matches then...
            return string.Empty;
        }

        protected string GenerateNamespaceIncludes(List<string> namespaceIncludes)
        {
            if (namespaceIncludes == null || namespaceIncludes.Count == 0)
                return string.Empty;

            var sb = new StringBuilder();

            namespaceIncludes.Sort();

            foreach (var item in namespaceIncludes)
            {
                string buffer = item.Trim();

                if (!string.IsNullOrEmpty(item))
                {
                    if (buffer.Contains(";"))
                        buffer = buffer.Replace(";", string.Empty);

                    sb.AppendLine($"using {buffer};");
                }
            }

            return sb.ToString();
        }

        // formatting methods 
        // todo - remove
        protected string PadCSharpVariableName(string input, int longest_string_length)
        {
            return PadVariableName(input, longest_string_length, 0, _VisualStudioTabSize);
        }
        protected string PadCSharpVariableName(string input, int longest_string_length, int padding)
        {
            return PadVariableName(input, longest_string_length, padding, _VisualStudioTabSize);
        }
    }
}